"""'admin'

Revision ID: 92341f71d0d4
Revises: d04248d70d79
Create Date: 2018-01-16 18:17:42.611214

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92341f71d0d4'
down_revision = 'd04248d70d79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('user_admin', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'user_admin')
    # ### end Alembic commands ###
